// Migration 01: creates the Users table (account identity, role, and status)
// Migration: up() applies schema changes, down() reverts them
"use strict";

import { UserRoles, UserStatus } from "@commons/user.ts";
import { DataTypes, type QueryInterface, type Sequelize } from "sequelize";

// Minimal logger so migration errors/info are easy to spot in console output
const migrationLogger = {
    error: (e: unknown) => {
        console.error("[Migrations]", e);
    },
    info: (...args: unknown[]) => {
        console.log("[Migrations]", ...args);
    },
};

// Creates the Users table
export async function up(queryInterface: QueryInterface, sequelize: Sequelize) {
    try {
        // Users: core account information
        await queryInterface.createTable("Users", {
            // Primary key: UUID generated by the application
            id: {
                type: DataTypes.UUID,
                allowNull: false,
                primaryKey: true,
            },
            // Login identity; unique across all users
            email: {
                type: DataTypes.STRING,
                allowNull: false,
                unique: true,
            },
            // Display name
            name: {
                type: DataTypes.STRING,
                allowNull: false,
            },
            // Role the user has
            role: {
                // Allowed roles; keep in sync with the UserRoles enum
                type: DataTypes.ENUM(...Object.values(UserRoles)),
                allowNull: false,
                defaultValue: UserRoles.GUEST,
            },
            // Account lifecycle state (invited -> active/inactive)
            status: {
                // Allowed statuses; keep in sync with the UserStatus enum
                type: DataTypes.ENUM(...Object.values(UserStatus)),
                allowNull: false,
                defaultValue: UserStatus.INVITED,
            },
            // Timestamps; deletedAt is set for soft deletes (paranoid models)
            createdAt: {
                type: DataTypes.DATE,
                allowNull: false,
            },
            updatedAt: {
                type: DataTypes.DATE,
                allowNull: true,
            },
            deletedAt: {
                type: DataTypes.DATE,
                allowNull: true,
            },
        });
    } catch (error) {
        migrationLogger.error(error);
        throw error;
    }
}

// Drops the Users table
export async function down(queryInterface: QueryInterface, sequelize: Sequelize) {
    try {
        await queryInterface.dropTable("Users");
    } catch (error) {
        migrationLogger.error(error);
        throw error;
    }
}

// Export both functions as the default export for the migration runner
export default { up, down };
