// Migration 04: creates the Files table (uploaded files attached to datasets)
// up() applies schema changes, down() reverts them
"use strict";

import { DataTypes, type QueryInterface, type Sequelize } from "sequelize";
import { FileTypes } from "@commons/file.ts";
// Minimal logger so migration errors/info are easy to spot in console output
const migrationLogger = {
    error: (e: unknown) => {
        console.error("[Migrations]", e);
    },
    info: (...args: unknown[]) => {
        console.log("[Migrations]", ...args);
    },
};

// Apply the migration
export async function up(queryInterface: QueryInterface, sequelize: Sequelize) {
    try {
        // add schema changes
        await queryInterface.createTable("Files", {
            // Primary key: UUID generated by the application
            id: {
                type: DataTypes.UUID,
                allowNull: false,
                primaryKey: true,
            },
            // Foreign key to Datasets.id: the dataset this file belongs to; deleting/updating the dataset cascades
            dataset_id: {
                type: DataTypes.UUID,
                allowNull: false,
                references: { model: "Datasets", key: "id" },
                onUpdate: "CASCADE",
                onDelete: "CASCADE",
            },
            // Foreign key to Users.id: the user that uploaded this file (no cascade; Users are soft-deleted)
            user_id: {
                type: DataTypes.UUID,
                allowNull: false,
                references: { model: "Users", key: "id" },
                onUpdate: "CASCADE",
                onDelete: "CASCADE",
            },
            // Kind of file (cover image, RDS, or raw data); values come from FileTypes
            type: {
                type: DataTypes.ENUM(...Object.values(FileTypes)),
                allowNull: false,
            },
            // File size in bytes
            sizeBytes: {
                type: DataTypes.BIGINT,
                allowNull: false,
            },
            // Original filename as uploaded by the user
            ogName: {
                type: DataTypes.STRING,
                allowNull: false,
            },
            // Timestamps (no deletedAt: files are hard-deleted so the unique (dataset_id, type) slot is freed)
            createdAt: {
                type: DataTypes.DATE,
                allowNull: false,
            },
            updatedAt: {
                type: DataTypes.DATE,
                allowNull: true,
            },
        });

        // Each dataset can have at most one file of each type
        // Added as a named constraint after createTable; the Files model declares the same name via @Unique("Files_dataset_id_type_unique")
        await queryInterface.addConstraint("Files", {
            fields: ["dataset_id", "type"],
            type: "unique",
            name: "Files_dataset_id_type_unique",
        });
    } catch (error) {
        migrationLogger.error(error);
        throw error;
    }
}

// Revert the migration
export async function down(queryInterface: QueryInterface, sequelize: Sequelize) {
    try {
        // revert schema changes
        await queryInterface.dropTable("Files");
        await (queryInterface as any).dropEnum("enum_Files_type");
    } catch (error) {
        migrationLogger.error(error);
        throw error;
    }
}

// Export both functions as the default export for the migration runner
export default { up, down };
