// Migration 04: creates the Files table (uploaded files attached to datasets)
// up() applies schema changes, down() reverts them
"use strict";

import { DataTypes, type QueryInterface, type Sequelize } from "sequelize";
import { FileTypes } from "@commons/file.ts";
// Minimal logger so migration errors/info are easy to spot in console output
const migrationLogger = {
    error: (e: unknown) => {
        console.error("[Migrations]", e);
    },
    info: (...args: unknown[]) => {
        console.log("[Migrations]", ...args);
    },
};

// Apply the migration
export async function up(queryInterface: QueryInterface, sequelize: Sequelize) {
    try {
        // add schema changes
        await queryInterface.createTable("Files", {
            // Primary key: UUID generated by the application
            id: {
                type: DataTypes.UUID,
                allowNull: false,
                primaryKey: true,
            },
            // Foreign key to Datasets.id: the dataset this file belongs to; deleting/updating the dataset cascades
            dataset_id: {
                type: DataTypes.UUID,
                allowNull: false,
                references: { model: "Datasets", key: "id" },
                onUpdate: "CASCADE",
                onDelete: "CASCADE",
            },
            // Foreign key to Users.id: the user that uploaded this file (cascades, so deleting a user also deletes the files they uploaded; Users are hard-deleted)
            user_id: {
                type: DataTypes.UUID,
                allowNull: false,
                references: { model: "Users", key: "id" },
                onUpdate: "CASCADE",
                onDelete: "CASCADE",
            },
            // Kind of file (cover image or RDS); values come from FileTypes
            type: {
                type: DataTypes.ENUM(...Object.values(FileTypes)),
                allowNull: false,
            },
            // File size in bytes
            sizeBytes: {
                type: DataTypes.BIGINT,
                allowNull: false,
            },
            // Original filename as uploaded by the user
            ogName: {
                type: DataTypes.STRING,
                allowNull: false,
            },
            // Version number of the file; (dataset_id, type, version) is unique
            version: {
                type: DataTypes.INTEGER,
                allowNull: false,
                defaultValue: 1,
            },
            // True for the most recent version of this type in the dataset; older versions stay as rows but their files are deleted from disk
            isCurrent: {
                type: DataTypes.BOOLEAN,
                allowNull: false,
                defaultValue: true,
            },
            // Notes on what changed since the previous version (only collected for RDS files)
            updates: {
                type: DataTypes.TEXT,
                allowNull: true,
            },
            // Timestamps (no deletedAt: files are hard-deleted so the unique (dataset_id, type, version) slot is freed)
            createdAt: {
                type: DataTypes.DATE,
                allowNull: false,
            },
            updatedAt: {
                type: DataTypes.DATE,
                allowNull: true,
            },
        });

        // Each dataset can have at most one file of each type and version
        // Added as a named constraint after createTable; the Files model declares the same name via @Unique("Files_dataset_id_type_version_unique")
        await queryInterface.addConstraint("Files", {
            fields: ["dataset_id", "type", "version"],
            type: "unique",
            name: "Files_dataset_id_type_version_unique",
        });

        // At most one current version per dataset and type (partial unique index; the Files model does not declare it)
        await queryInterface.addIndex("Files", ["dataset_id", "type"], {
            unique: true,
            name: "Files_dataset_id_type_current_unique",
            where: { isCurrent: true },
        });
    } catch (error) {
        migrationLogger.error(error);
        throw error;
    }
}

// Revert the migration
export async function down(queryInterface: QueryInterface, sequelize: Sequelize) {
    try {
        // revert schema changes
        await queryInterface.dropTable("Files");
        await (queryInterface as any).dropEnum("enum_Files_type");
    } catch (error) {
        migrationLogger.error(error);
        throw error;
    }
}

// Export both functions as the default export for the migration runner
export default { up, down };
