// Migration 05: creates the Activities table (log of user and system events)
// up() applies schema changes, down() reverts them
"use strict";

import { DataTypes, type QueryInterface, type Sequelize } from "sequelize";
import { ActivityType } from "@commons/activity.ts";
// Minimal logger so migration errors/info are easy to spot in console output
const migrationLogger = {
    error: (e: unknown) => {
        console.error("[Migrations]", e);
    },
    info: (...args: unknown[]) => {
        console.log("[Migrations]", ...args);
    },
};

// Apply the migration
export async function up(queryInterface: QueryInterface, sequelize: Sequelize) {
    try {
        // add schema changes
        await queryInterface.createTable("Activities", {
            // Primary key: UUID generated by the application
            id: {
                type: DataTypes.UUID,
                allowNull: false,
                primaryKey: true,
            },
            // Foreign key to Users.id: the user who performed the activity
            user_id: {
                type: DataTypes.UUID,
                allowNull: false,
                references: { model: "Users", key: "id" },
            },
            // Type of activity logged
            type: {
                type: DataTypes.ENUM(...Object.values(ActivityType)),
                allowNull: false,
            },
            // Data from the activity
            // JSON column; shape varies by ActivityType
            data: {
                type: DataTypes.JSON,
                allowNull: false,
            },
            // Timestamps; deletedAt is set for soft deletes (paranoid models)
            createdAt: {
                type: DataTypes.DATE,
                allowNull: false,
            },
            updatedAt: {
                type: DataTypes.DATE,
                allowNull: true,
            },
            deletedAt: {
                type: DataTypes.DATE,
                allowNull: true,
            },
        });
    } catch (error) {
        migrationLogger.error(error);
        throw error;
    }
}

// Revert the migration
export async function down(queryInterface: QueryInterface, sequelize: Sequelize) {
    try {
        // revert schema changes
        await queryInterface.dropTable("Activities");
        await (queryInterface as any).dropEnum("enum_Activities_type");
    } catch (error) {
        migrationLogger.error(error);
        throw error;
    }
}

// Export both functions as the default export for the migration runner
export default { up, down };
